package model.types;

public enum EventPropertyType {
    GAME_LENGTH,
    COUNTRY,
    RACE_DISTANCE,
    RACE_NUMBER,
    GOING_INFORMATION,
    GROUP_ID,
    GROUP_STATUS,
    EVENT_STAGE,
    NUMBER_OF_RUNNERS,
    MAXIMUM_NUMBER_OF_RUNNERS,
    HANDICAP,
    GROUP_TYPE,
	EVENT_STATUS
}