cassandra:
  build: docker/cassandra
  hostname: cassandra01
  domainname: cassandra01.dev.docker
  ports:
   - "9042:9042"
   - "9160:9160"

rabbitmq:
    build: docker/rabbitmq
    hostname: rabbitmq
    command: rabbitmq-server start
    ports:
        - "5672:5672"
        - "15672:15672"